### ISSUE TITLE
sidebery_styles.css 不适配白色主题

### ISSUE THREAD

**Issue by immadolf** [christorange/VerticalFox#1]
我删除了这一段样式后
```css
	/* Dark Theme base settings */
	--bg: #1a1b26 !important;
	--tabs-fg: #d4d4d4 !important;
	--tabs-bg-hover: #3b3948 !important;
	--tabs-activated-bg: #5b5b66 !important;
	--nav-btn-activated-bg: #1f222f !important;
```

上面的几个按钮就看不清了
<img width="331" alt="图片" src="https://user-images.githubusercontent.com/12369197/230523389-10ab8f2d-716a-4c3a-bbda-67bcea981624.png">

**Comment by christorange** [comment]
这几个按钮的样式由 `.NavigationBar.panel-btn` 控制，你可以找到那一行更改，我也更新了下这个文件。不过目前确实是只为了dark mode写的

**Comment by immadolf** [comment]
不好意思，我对css不熟悉，能麻烦帮忙写一个亮色的样式吗

**Comment by christorange** [comment]
亮色主题已更新！浏览器配色也增加了浅色配色，具体请参考新的 [安装指南](https://github.com/christorange/VerticalFox/blob/main/readme_ch.md)

**Comment by immadolf** [comment]
感谢！
