### ISSUE TITLE
auto模式主题显示不正常

### ISSUE THREAD

**Issue by Aurora-Simba** [christorange/VerticalFox#11]
![屏幕截图 2023-06-04 105139](https://github.com/christorange/VerticalFox/assets/106955617/86c93d25-e7c9-4681-9867-000a44b183ad)
![屏幕截图 2023-06-04 105157](https://github.com/christorange/VerticalFox/assets/106955617/074bff58-5ac2-4db3-b910-0bd7fd60d984)

auto不正常，light正常

**Comment by christorange** [comment]
系统主题为深色的情况下 theme 设置为 auto 是深色外观，light 是浅色外观，系统主题为浅色时只能选择 light，其他选项会有异常，只用一个 `userChrome.css` 文件来做双主题适配的话，目前社区里也没有看到更好的实现方案，大多数需要手动运行另外的 shell 文件去切换 `userChrome.css` 来切换主题
