### ISSUE TITLE
最新版Firefox出现问题

### ISSUE THREAD

**Issue by Aurora-Simba** [christorange/VerticalFox#14]
![图片](https://github.com/christorange/VerticalFox/assets/106955617/79e00821-40b7-4ec2-973e-47e303e16010)
![屏幕截图 2023-08-30 115858](https://github.com/christorange/VerticalFox/assets/106955617/a877d1b1-b943-4d19-bd77-67a280f2f996)

**Comment by Aurora-Simba** [comment]
上一版无问题

**Comment by ylzty** [comment]
> ![图片](https://user-images.githubusercontent.com/106955617/264222664-79e00821-40b7-4ec2-973e-47e303e16010.png) ![屏幕截图 2023-08-30 115858](https://user-images.githubusercontent.com/106955617/264263777-a877d1b1-b943-4d19-bd77-67a280f2f996.png)

我也发现了同样的问题。
