### ISSUE TITLE
配置完后，在工具栏二级菜单字体对比度较差，难以看清

### ISSUE THREAD

**Issue by Mosazh** [christorange/VerticalFox#15]

**Comment by Mosazh** [comment]
![屏幕截图 2023-09-21 181430](https://github.com/christorange/VerticalFox/assets/67796267/cff72201-18b8-4c5e-9daa-cb2146808fd0)

**Comment by christorange** [comment]
在浏览器设置的扩展与主题中启用亮色配色
<img width="221" alt="image" src="https://github.com/christorange/VerticalFox/assets/85213835/a6d33983-fbff-485c-9645-dc30885c0dbd">

<img width="725" alt="image" src="https://github.com/christorange/VerticalFox/assets/85213835/24f5d339-771e-4340-acc4-fa295f940b17">
