### ISSUE TITLE
配置完成后如何方便打开新标签页

### ISSUE THREAD

**Issue by ABazingaE** [christorange/VerticalFox#16]
您好，您的代码很有帮助！但我有个困惑，在更改样式之前，浏览器最后一个标签页后面会紧跟一个加号按钮，
![issue](https://github.com/christorange/VerticalFox/assets/55418219/817075ad-7ec7-432b-873e-948a93644bc4)

点击可以方便新建标签页，样式更改之后如何做到相同的操作呢

**Comment by christorange** [comment]
双击侧边栏空白处即可
![Kapture 2023-09-22 at 00 52 40](https://github.com/christorange/VerticalFox/assets/85213835/fb5c51e1-665f-4493-990f-433f0f09046c)
