### ISSUE TITLE
The style is broken with Sideberry 5.0.0

### ISSUE THREAD

**Issue by villivateur** [christorange/VerticalFox#17]
Here is the screenshot:

![image](https://github.com/christorange/VerticalFox/assets/30222160/9b3a3d72-e4d9-4d1c-ae6e-71e670591e22)

And the version:

![image](https://github.com/christorange/VerticalFox/assets/30222160/1258a911-f7b8-4abf-8a5b-6fc40da6b066)

**Comment by Aurora-Simba** [comment]
I have the same problem.

**Comment by christorange** [comment]
Please go to https://addons.mozilla.org/en-US/firefox/addon/sidebery/versions/ , remove the latest Sideberry and install v4.10, re-apply the [sidebery_styles.css](https://github.com/christorange/VerticalFox/blob/main/sidebery/sidebery_styles.css).

This issue has happened on may other Sidebery users: https://github.com/mbnuqw/sidebery/issues/1241

Personally I'm very disappointed with this update, Sidebery disabled a lot of CSS custom options so my original custom css setup cannot work at all now. I can do nothing than keeping track of this issue, and hope Sidebery team will fix this shitty update.

**Comment by Elementari** [comment]
Perhaps a list of css option of this kind might be helpful:
CSS options... 
1.1 that continued to work like in v4 
1.2 ... but have some issue (values not carried over from v4 e.g., values having a different effect)
2.1 that have been removed and replaced by new option X
2.2 that have been removed with no replacement
3. that have been newly added

In Style Editor, I see commented out lines in "Gruppenseite" (group page?), but none in "Seitenleiste" even though I am pretty sure I only changed stuff in Seitenleiste.

Gruppenseite:
/* OLD CSS VARS
#root.root {--tabs-height: 17px;}
#root.root {--tabs-pinned-height: 21px;}
#root.root {--tabs-indent: 23px;}
#root.root {--tabs-font: .8rem sans-serif;}
*/

**Comment by christorange** [comment]
Finally resolved in the latest release https://github.com/christorange/VerticalFox/releases/tag/v1.4.0
