### ISSUE TITLE
垂直侧边栏与顶部存在色差

### ISSUE THREAD

**Issue by lsdxfs** [christorange/VerticalFox#19]
![image](https://github.com/christorange/VerticalFox/assets/115888450/23f36167-eada-4a59-a3ed-bb3ad6456b93)

**Comment by Aurora-Simba** [comment]
请回退sidebery版本

**Comment by christorange** [comment]
Sidebery v5 的破坏性更新让很多 css 选择器失效了，只能暂时使用 v4

> ❗️❗️If you're, or going to use this setup, DO NOT UPGRADE TO Sidebery v5. If you have, remove it and install v4.10 [here](https://addons.mozilla.org/en-US/firefox/addon/sidebery/versions/), then turn off auto update.
