### ISSUE TITLE
URL bar transparency

### ISSUE THREAD

**Issue by cosing** [christorange/VerticalFox#2]
![图片](https://user-images.githubusercontent.com/63569926/231348032-3a6898c2-b380-4d40-85e3-47322b457223.png)

CN：这是正常的吗？URL是透明的，如图所示，Windows上的firefox
EN：Is this normal? The URL is transparent, as shown in the image, firefox on Windows

ps：
CN：哦，我发现了，这似乎和我的主题有关，我更换主题为染山霞后事情发生了改变，虽然看上去更奇怪了，但当我把主题换成明亮时，这一切合理了起来。
EN：Oh, I found it, it seems to be related to my theme, things changed after I changed the theme to Alpenglow, although it looks stranger, but it all made sense when I changed the theme to Bright.

![图片](https://user-images.githubusercontent.com/63569926/231348713-e125c359-799c-4b4b-92cb-bdd600ac7cff.png)

**Comment by christorange** [comment]
`userChrome.css` 中大多数样式都带有 `!important`，所以会覆盖浏览器的样式，使用非默认主题的话确实会不兼容，推荐将system theme 设置为 auto
