### ISSUE TITLE
这个能不能只显示图标？或者把字移开点？

### ISSUE THREAD

**Issue by EnderAvaritia** [christorange/VerticalFox#20]
![Snipaste_2023-10-11_10-19-04](https://github.com/christorange/VerticalFox/assets/84321282/796f4b6a-9bc0-4711-a661-97eab49927b7)

**Comment by christorange** [comment]
实际效果应为
![image](https://github.com/christorange/VerticalFox/assets/85213835/ead24298-08a8-4a6b-a425-39034c671f75)
可以参考 README 动图。

请确保完成了这一步

![image](https://github.com/christorange/VerticalFox/assets/85213835/3a75bb75-88c5-4c91-a3dd-8c933ea7e3da)

**Comment by EnderAvaritia** [comment]
谢谢，这个是我看漏了
