### ISSUE TITLE
这个区域的透明度是哪条语句控制的？

### ISSUE THREAD

**Issue by EnderAvaritia** [christorange/VerticalFox#21]
![Snipaste_2023-10-11_10-24-01](https://github.com/christorange/VerticalFox/assets/84321282/295826ba-3b8c-4ade-8c7b-8340f3cbb85d)

**Comment by EnderAvaritia** [comment]
在自动主题下地址栏背景不能正常显示，改成明亮后正常，深邃也正常

**Comment by EnderAvaritia** [comment]
以及，深邃的背景颜色是不是出了什么问题？
![Snipaste_2023-10-11_12-10-24](https://github.com/christorange/VerticalFox/assets/84321282/da81f6f4-8e94-45f9-a216-5ca3c5b84fa3)

**Comment by christorange** [comment]
如果希望浏览器外观为亮色，网页为深色，只更改网页配色而非浏览器主题

![image](https://github.com/christorange/VerticalFox/assets/85213835/a6e3c663-bef5-456a-8e68-deef98d3fbd0)

**Comment by EnderAvaritia** [comment]
> 如果希望浏览器外观为亮色，网页为深色，只更改网页配色而非浏览器主题
> 
> ![image](https://user-images.githubusercontent.com/85213835/274172278-a6e3c663-bef5-456a-8e68-deef98d3fbd0.png)

不是希望改变浏览器外观，在自动配色下，地址栏的背景显示为透明，而选择明亮/深邃配色，地址栏背景至少是有的，这个是刻意的设计还是真出了问题

**Comment by christorange** [comment]
要使用亮色配色，浏览器主题必须设置为明亮。#15
要使用深色主题，必须如下设置：
<img width="864" alt="image" src="https://github.com/christorange/VerticalFox/assets/85213835/a710c898-b672-4027-8b14-35c5a8b9c745">

**Comment by EnderAvaritia** [comment]
> 要使用亮色配色，浏览器主题必须设置为明亮。#15 要使用深色主题，必须如下设置： <img alt="image" width="864" src="https://user-images.githubusercontent.com/85213835/274209154-a710c898-b672-4027-8b14-35c5a8b9c745.png">

啊……好吧……我大概明白是怎么回事了
也就是说这东西不支持把主题设置成自动？

**Comment by christorange** [comment]
是的，虽然编写时就是使用媒体查询检测浏览器主题，但是实际用时必须这样才能让所有元素配色正常，只是免去了切换配色时手动更换 `userChrome.css` 的麻烦

**Comment by EnderAvaritia** [comment]
> 是的，虽然编写时就是使用媒体查询检测浏览器主题，但是实际用时必须这样才能让所有元素配色正常，只是免去了切换配色时手动更换 `userChrome.css` 的麻烦

好的，谢谢

**Comment by christorange** [comment]
在  [最新版](https://github.com/christorange/VerticalFox/releases/tag/v1.2.2) 修复了这个问题，现在主题可以完全自动跟随系统偏好了

**Comment by EnderAvaritia** [comment]
> 在 [最新版](https://github.com/christorange/VerticalFox/releases/tag/v1.2.2) 修复了这个问题，现在主题可以完全自动跟随系统偏好了

谢谢大佬
