### ISSUE TITLE
Style is broken on firefox 119

### ISSUE THREAD

**Issue by duonqHoang** [christorange/VerticalFox#22]
url search result background is transparent, and there is white line under nav bar
OS: windows 10
![image](https://github.com/christorange/VerticalFox/assets/79439580/290bad2a-5d1b-4740-9f65-f5f71eb8c67f)

**Comment by christorange** [comment]
> [Frequently Asked](https://github.com/christorange/VerticalFox/blob/main/README.md#frequently-asked)
Q: Dark mode doesn't work (or behaves abnormally).
A: Set your system theme as dark, then set your Firefox theme as 'auto' in Extensions & Themes. If it still doesn't work, go to releases and use the files in the dark only release.

**Comment by duonqHoang** [comment]
still not working. I got the bug after updating firefox to version 119 
![image](https://github.com/christorange/VerticalFox/assets/79439580/5022d485-92cf-4cd4-9a93-557ba615fe93)

**Comment by CCRcmcpe** [comment]
I ran into this problem too with 119.

**Comment by Mom0w** [comment]
Same issue here

**Comment by christorange** [comment]
It's due to the dark theme selector change in 119 update, will publish a new release soon

**Comment by christorange** [comment]
Fixed in the [latest release](https://github.com/christorange/VerticalFox/releases/tag/v1.2.2), and theme switch following system color preference is fixed too :p

**Comment by duonqHoang** [comment]
Nice, Thanks a lot
