### ISSUE TITLE
The contrast between the background color and text color is too low in light theme

### ISSUE THREAD

**Issue by ProudBenzene** [christorange/VerticalFox#28]
Hi, this Vertical Tabs really works very well and greatly improves the productivity of Firefox!

But I found that the contrast between the background color and text color is too low in light theme, for example:

<img width="424" alt="图片" src="https://github.com/christorange/VerticalFox/assets/93238080/be43509a-4713-43c5-9c76-88b82b69d56a">

I have tried to modify the CSS color scheme myself, but I am not very familiar with Firefox's CSS settings. I only successfully modified the color scheme of the uri bar:

<img width="497" alt="图片" src="https://github.com/christorange/VerticalFox/assets/93238080/ba2d4569-1e52-460d-9dd3-40148231239c">

I wonder if you could please modify the color scheme in light mode, thanks!

**Comment by christorange** [comment]
It seems you are applying the Firefox Alpenglow theme, rather than the default light theme

![image](https://github.com/christorange/VerticalFox/assets/85213835/fc5ae5b8-ff43-450f-9ad4-88305e4085c7)

This CSS setup is based on the default Firefox themes, hence incompatible with other themes.
