### ISSUE TITLE
顶部菜单能否更贴合工具栏？应该调整什么参数

### ISSUE THREAD

**Issue by jojo552** [christorange/VerticalFox#29]
![捕获](https://github.com/christorange/VerticalFox/assets/39025926/0204789f-5a7b-4314-942f-681ee2302759)
指定是图片红框的部分

**Comment by Like-rainer** [comment]
你好，工具栏右侧的三个窗口控制按钮丢失该怎么恢复？翻新Firefox并不可以
![图片](https://github.com/christorange/VerticalFox/assets/98692156/c4453e12-8e1f-4494-8a60-f0ed639a8387)

**Comment by yjlintw** [comment]
> ![捕获](https://private-user-images.githubusercontent.com/39025926/292389599-0204789f-5a7b-4314-942f-681ee2302759.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MDIzNTksIm5iZiI6MTcwMzgwMjA1OSwicGF0aCI6Ii8zOTAyNTkyNi8yOTIzODk1OTktMDIwNDc4OWYtNWE3Yi00MzE0LTk0MmYtNjgxZWUyMzAyNzU5LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIyMjA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjdhMzQxM2M0YmRjZWZlMzMzNzBmMjVjNmNkZDliOTUyZDU2MzAxZWY3ZmFkYWM4NDIxZDVlNWI0ZWQwNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rkBPphnlRL6QKC_tGoB9tj09BkzNbrX09upiKTjDwV8) 指定是图片红框的部分

in userChrome.css, under line 252 (selector is `#nav-bar #PanelUI-button #PanelUI-menu-button`)
change `margin-right` from 40px to 2px
```css
#nav-bar #PanelUI-button #PanelUI-menu-button {
   margin-right: 2px !important; /* this line */
   margin-left: 2px !important;
}
```

**Comment by christorange** [comment]
已于最新版移除该空白。
