### ISSUE TITLE
如何设置垂直标签页自动伸缩

### ISSUE THREAD

**Issue by LionLin2003** [christorange/VerticalFox#3]
您好，想请教一下如何在插件中设置垂直标签页自动伸缩

**Comment by christorange** [comment]
配置好`userChrome.css`后就有自动伸缩，不在插件里设置，请确保每一步都按照[安装说明](https://github.com/christorange/VerticalFox/blob/main/readme_ch.md)

**Comment by LionLin2003** [comment]
感谢！
