### ISSUE TITLE
更新FireFox 123版本后 最小化/最大化/关闭按钮 不可见 也不可点击

### ISSUE THREAD

**Issue by Mithual** [christorange/VerticalFox#30]
1. 更新FireFox Nightly 123版本后 最小化/最大化/关闭按钮 不可见 也不可点击
2. 此外在鼠标拖动标题栏时,菜单按钮到最右侧治具的部分不能拖动
![图片](https://github.com/christorange/VerticalFox/assets/27963026/54324979-a690-4b61-ac99-7381b839fa75)
--- 
以上,样式文件应该修改哪里?

**Comment by Mithual** [comment]
目前找到的解决方式；在[定制工具栏]处启用[标题栏]暂时可用,期待更新解决

**Comment by choicky** [comment]
我用最新版的vertical [1.3.2](https://github.com/christorange/VerticalFox/releases/tag/v1.3.2) ，Firefox 之前是122，一切正常。
后来Firefox自动升级到123，`最小化` `最大化` `关闭` 按钮就不见了，重装 vertical 也一样
