### ISSUE TITLE
title bar top margin too small in Firefox 122

### ISSUE THREAD

**Issue by wintericie** [christorange/VerticalFox#34]
Platform: MacOS Sonoma 14.2.1, Firefox 122 (Stable)

I updated my Firefox to version 122 and found that the top margin has become narrower than before. Screenshots are attached below.

Normal window:
<img width="1387" alt="image" src="https://github.com/christorange/VerticalFox/assets/5930472/30f8d77f-9151-4408-9eca-c42b0ecc7ede">

Fullscreen window:
<img width="710" alt="image" src="https://github.com/christorange/VerticalFox/assets/5930472/58968aec-284a-46d4-bbeb-51e0c42e0955">

It seems the Firefox update has broken some styles regarding the title bar. I have tried to add `margin-top: 15px` to `toolbar#TabsToolbar .titlebar-buttonbox-container`, but it only works for normal windows but not fullscreen ones. Would it be possible to get this addressed in the future? Thanks.

**Comment by wintericie** [comment]
Figured out a temporary fix: Besides the `.titlebar-buttonbox-container` setting, also set `margin-top` in `#nav-bar[inFullscreen="true"]` to `0`.

**Comment by christorange** [comment]
Thank you for notifying this, resolved in the latest release:

https://github.com/christorange/VerticalFox/releases/tag/v1.3.2
