### ISSUE TITLE
If you close all tabs, you can't add new tabs

### ISSUE THREAD

**Issue by xxt115** [christorange/VerticalFox#35]
When all tabs are closed, you can't add new tabs, I don't know if it's the project or Sidebery's problem
You can try to circumvent this problem by changing browser.tabs.closeWindowWithLastTab ，so that the Firefox homepage automatically opens when the last tab is closed.

**Comment by christorange** [comment]
Sadly this is not what I can control with CSS, but as you mentioned you can achieve what you want by toggle that option in `about:config`:
https://support.mozilla.org/en-US/questions/1205166
