### ISSUE TITLE
浏览器123版本右上角按钮消失

### ISSUE THREAD

**Issue by lolo77777** [christorange/VerticalFox#36]
浏览器升级到123版本后，右上角的最小化最大化关闭按钮不见了

**Comment by marcosteam** [comment]
临时的解决办法是把菜单栏显示出来，不过会很丑

**Comment by lolo77777** [comment]
> 临时的解决办法是把菜单栏显示出来，不过会很丑

好的

**Comment by newmyl** [comment]
我已经将firefox降级到122版本了。或者用另外一个作者提供的userchrome.css也行，这里就不贴了。

**Comment by pangpilolo** [comment]
> 临时的解决办法是把菜单栏显示出来，不过会很丑

你好，怎么显示菜单栏？

**Comment by lolo77777** [comment]
> > 临时的解决办法是把菜单栏显示出来，不过会很丑
> 
> 你好，怎么显示菜单栏？

右键点网址那一栏附近空白的地方，选定制工具栏，右下角有个标题栏，选中就可以了

**Comment by lolo77777** [comment]
这里附上另一个[链接](https://github.com/yuzhi535/VerticalFox)。他没有插件样式的部分，还是没有当前库的美观，不过可以结合一下当前库的插件样式，暂时解决这个问题。

**Comment by alsjiop** [comment]
> 这里附上另一个 [链接 ](https://github.com/yuzhi535/VerticalFox)。他没有插件样式的部分，还是没有当前库的美观，不过可以结合一下当前库的插件样式，暂时解决这个问题。

我是把另一个Hides tabs toolbar的内容拉过来,然后把当前库的Close/min/max fix里面的#navigator-toolbox开始到Line up前全注释掉,就能解决

**Comment by alsjiop** [comment]
> > 我已经将firefox降级到122版本了。或者用另外一个作者提供的userchrome.css也行，这里就不贴了。
> 
> 求另一作者的链接，哈哈

https://github.com/christorange/VerticalFox/issues/36#issuecomment-1960950630

**Comment by christorange** [comment]
增加以下样式即可解决：
```CSS
#nav-bar{
	position: static !important;
}
```
已修复于最新版 https://github.com/christorange/VerticalFox/releases/tag/v1.4.0
