### ISSUE TITLE
丢失标签页的风险

### ISSUE THREAD

**Issue by cosing** [christorange/VerticalFox#4]
复现过程：当开启隐私窗口后，关闭主窗口，此时再次开启主窗口标签页会丢失。
应该是那个插件的问题，我目前人有点恍惚，先在这里提个醒，或者是火狐的问题？不记得原版火狐如何表现了。

**Comment by christorange** [comment]
和隐私窗口无关，确实关闭浏览器后再打开不会自动恢复之前的窗口，但是可以从浏览历史的 recently closed windows 中恢复。测试了另一个主流的侧边栏插件 Tree Style Tabs，情况相同，应该是浏览器插件的局限

**Comment by cosing** [comment]
实际上这里应该遵循firefox的设置，在我之前一直表现的挺好的：
启动
打开先前的窗口和标签页(S)

定义表现正常：
即打开浏览器，打开标签页abcd，打开隐私模式浏览器，打开标签页e，关闭浏览器，关闭隐私模式浏览器
然后再次打开浏览器，此时会完美的保留abcd

没现成的空白firefox，懒得创建profile了
在没进行任何额外配置的developer edition上测试，表现正常

但是如果单独只使用了Sidebery，仍然表现正常，但是我注意到了这一点，即单独只使用Sidebery时候开启隐私模式的时候，标签组图标和tag应该是如此的。
![图片](https://user-images.githubusercontent.com/63569926/236414020-bef683d9-82f6-4235-ad21-ea3c3d984c37.png)

嗯，我发现仍然可能是我那一步配置出现问题或者与其他插件出现问题了，我新开了个空白的firefox，配置好之后也像上面那样，但是对于我一开始用的profile，就是下面这样了，然后估计就是插件没识别到这是一个隐私窗口，导致最后覆盖了default的行为。
![图片](https://user-images.githubusercontent.com/63569926/236417273-774a3cef-d296-470a-bda6-f933573612ca.png)

总的来说结论：当隐私窗口中的Sidebery成为这样的时候最好不要先关闭主窗口，虽然仍然不知道为什么会发生这种事情，我把Sidebery给reset setting了也不管用。

**Comment by cosing** [comment]
因为手残卸掉了，然后再安装回来就无法复现了...

总得来说很奇怪。我觉得我应该首先去上游插件找找。

**Comment by christorange** [comment]
下了 Developer edition 进行测试（没有自定义样式没有安装sidebery），确定开启了 open previous windows and tabs, 重启也没有恢复之前的标签页🤯 机器是M1的macbook。应该就是 Firefox 自己的问题，一点点css肯定是没法对浏览器逻辑造成影响的，sidebery 读的也是浏览器的标签页信息（更何况我测试没装sidebery与任何插件）。

由于可以确定不是本项目的锅所以先关闭这个 issue 不过非常欢迎继续探讨这个奇怪的bug（你也许可以去逛逛 [bugzilla](https://bugzilla.mozilla.org/home)
