### ISSUE TITLE
网址栏被遮挡

### ISSUE THREAD

**Issue by Like-rainer** [christorange/VerticalFox#44]
![Uploading 屏幕截图 2024-04-08 184008.png…]()
Firefox nightly 126.0a1
地址栏会被遮挡

**Comment by Like-rainer** [comment]
![屏幕截图 2024-04-08 184023](https://github.com/christorange/VerticalFox/assets/98692156/8d85a15e-5b47-4a0d-a706-8bf09fa90153)

**Comment by kongk856** [comment]
#urlbar-container{
   margin-bottom: 3px;
   display: initial;
}

如上 #urlbar-container 元素中加个这个样式 display: initial;

**Comment by Like-rainer** [comment]
很抱歉现在才回复您。您的帮助非常有用，再次感谢

**Comment by EnderAvaritia** [comment]
> #urlbar-container{ margin-bottom: 3px; display: initial; }
> 
> 如上 #urlbar-container 元素中加个这个样式 display: initial;

谢谢，今天firefox更新之后我也遇到了这个问题

**Comment by Mc-GrowlR** [comment]
感谢，在更新126版本之后也是遇到了这个问题，加上了这个样式之后就解决了

> #urlbar-container{ margin-bottom: 3px; display: initial; }
> 
> 如上 #urlbar-container 元素中加个这个样式 display: initial;
