### ISSUE TITLE
建议栏异常

### ISSUE THREAD

**Issue by Aurora-Simba** [christorange/VerticalFox#49]
![屏幕截图 2024-05-19 201258](https://github.com/christorange/VerticalFox/assets/106955617/543d74b5-f7fc-4e62-97e3-d388afdd035d)
Firefox 126.0

**Comment by jackeywcy** [comment]
同样出现了该问题，补充说明如下：
1. 更新firefox 为126.0 (64-bit 后，点击地址栏输入后，地址栏建议最上端覆盖住了原来的地址栏如图
![image](https://github.com/christorange/VerticalFox/assets/20952447/1d563914-5138-4c05-9fcc-c2dc370c38f0)

**Comment by 0x-y4c0** [comment]
Having the same problem, please let me know if you find a fix!

**Comment by C8H7N** [comment]
> Having the same problem, please let me know if you find a fix!

将79行和80行的代码注释掉
```css
  /* top: calc(
     (var(--urlbar-toolbar-height) - var(--urlbar-height)) ) !important; */
```
换成
```css
  top: 4px !important;
```
可能不是很完美 但至少能用

**Comment by C8H7N** [comment]
> Having the same problem, please let me know if you find a fix!

同时也可以参考https://github.com/christorange/VerticalFox/issues/44

**Comment by natesubra** [comment]
> > Having the same problem, please let me know if you find a fix!
> 
> 将79行和80行的代码注释掉
> 
> ```css
>   /*top: calc(
>      (var(--urlbar-toolbar-height) - var(--urlbar-height)) / 2 ) !important;*/
> ```
> 
> 换成
> 
> ```css
>   top: 4px !important;
> ```
> 
> 可能不是很完美 但至少能用

Confirming that @C8H7N 's fix works, removing lines 79-80 and replacing resolved this for me.

**Comment by christorange** [comment]
Fixed in latest release https://github.com/christorange/VerticalFox/releases/tag/v1.4.1
