### ISSUE TITLE
The site panel cut to half when fullscreen

### ISSUE THREAD

**Issue by wuqiangroy** [christorange/VerticalFox#51]
fullscreen:
<img width="1844" alt="image" src="https://github.com/christorange/VerticalFox/assets/21157586/475c7572-aeb5-4276-85b3-1e40d5075df1">
normal:
<img width="1661" alt="image" src="https://github.com/christorange/VerticalFox/assets/21157586/205851a0-6b1c-47b3-9072-f98db67568d7">

Env:
MacOS 12.3.1
Firefox: 127.0
VerticalFox version: 1.4.1

**Comment by wintericie** [comment]
Somehow the selector `#nav-bar[inFullscreen="true"]` on line 200 should be changed into `:root[inFullscreen='true'] #nav-bar`. Thanks for the insight from the latest reply in #34 from @dahliavkarma.
