### ISSUE TITLE
地址栏消失

### ISSUE THREAD

**Issue by meihanai** [christorange/VerticalFox#6]
你好，windows的水狐浏览器使用的时候，地址栏消失不见了。。想问一下怎么做才能正常
![image](https://github.com/christorange/VerticalFox/assets/131862741/f5430cd8-8de9-4e07-a1a4-ef4b6ae8f80b)

**Comment by christorange** [comment]
Waterfox 的默认外观与 Firefox 不同所以该主题不适用，你可以尝试只启用 `userChrome.css` 328行开始的代码，不影响浏览器外观，只涉及侧边栏自动收缩功能

**Comment by Aurora-Simba** [comment]
> 

![image](https://github.com/christorange/VerticalFox/assets/106955617/5d73e01c-cb7e-4bb2-9f5f-8d361ff35639)
新建chrome文件夹并配置文件后会出现这个选项，disable就好了

**Comment by Aurora-Simba** [comment]
![image](https://github.com/christorange/VerticalFox/assets/106955617/43094590-1559-4791-92d3-d885e9ea51bb)
容易误触最小化，能不能修改一下
