### ISSUE TITLE
抓个小虫，Mac v1.4.1 的页面缩放图标

### ISSUE THREAD

**Issue by ZTB888** [christorange/VerticalFox#62]
好像有一丢丢不协调
<img width="221" alt="截屏2024-10-13 19 09 44" src="https://github.com/user-attachments/assets/2b9d5183-390a-4612-a751-b01bb9496e2e">
能够居中的话好像会更好看诶！

**Comment by christorange** [comment]
在 https://github.com/christorange/VerticalFox/releases/tag/v1.5.0 修复了
