### ISSUE TITLE
升级到Firefox 133.0 地址栏宽度会占满浏览器

### ISSUE THREAD

**Issue by GitHubd3b7c** [christorange/VerticalFox#69]
![B4](https://github.com/user-attachments/assets/8997cab7-6a5b-4a48-8f9c-7ffa960bd572)
![AFT](https://github.com/user-attachments/assets/2c06b6b6-2a10-4ff0-bda2-7ccc5cb31df3)

应该是 userChrome.css 的问题，但不知道应该如何修改

配置文件用的是 1.5 release

**Comment by picpo** [comment]
#urlbar[breakout][breakout-extend]的宽度直接继承了浏览器的
我提交个pr试试

**Comment by GitHubd3b7c** [comment]
> #urlbar[breakout][breakout-extend]的宽度直接继承了浏览器的 我提交个pr试试

感谢，Windows同样有效 #70
