### ISSUE TITLE
误触

### ISSUE THREAD

**Issue by Aurora-Simba** [christorange/VerticalFox#9]
![image](https://github.com/christorange/VerticalFox/assets/106955617/43094590-1559-4791-92d3-d885e9ea51bb)
容易误触最小化，能不能修改一下

**Comment by christorange** [comment]
菜单按钮和最小化按钮之间是应该有一个固定间距的，而且菜单按钮应该在右侧，如下图：
![image](https://github.com/christorange/VerticalFox/assets/85213835/57e30bc8-9c9d-428d-8025-4ffe62ef9829)

请确保使用了最新的release 并且更新 firefox 到最新稳定版
